DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
    USERNAME      VARCHAR(100) NOT NULL,
    ROLE          VARCHAR(20) NOT NULL
);

CREATE TABLE FEEDBACK (
    ID          VARCHAR(50) NOT NULL,
    USERNAME    VARCHAR(100) NOT NULL,
    COMMENTS    VARCHAR(1024) NOT NULL,
    RATING      NUMBER(2) NOT NULL,
);